import Head from 'next/head'
import React from 'react'
import HomeContainer from '../containers/homeContainer'
export default function Home(initData) {
  return (
    <div className='container'>
      <Head>
        <title>Giffy App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/styles.css" />
        <meta name="discription" content="This app is creating for search Gifs"/>
      </Head>

      <HomeContainer data={initData.dogGif.data} />
    </div>
  )
}

export async function getStaticProps(){
  let dogGif = await fetch('https://api.giphy.com/v1/gifs/search?q=dogs&api_key=anNByDpkJV9JZWkx1Lbl7veRSn2UpF9L&limit=10')
  dogGif = await dogGif.json()
  return{props: {dogGif}}
}
